# Nom de l'application
spring.application.name=fluxExtractor

# Configuration de la source de données (Version Hardcodée)
spring.datasource.url=jdbc:postgresql://localhost:5432/fluxextractor_db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Stratégie Hibernate : Mise à jour automatique des tables
# Note : La base "fluxextractor_db" doit déjà exister dans Postgres
spring.jpa.hibernate.ddl-auto=update

# Feedback : Le 'database-platform' a été retiré (auto-détection Hibernate 6+)

# Logs et Debug
logging.level.org.hibernate.SQL=DEBUG
# Affiche les valeurs des paramètres dans les requêtes SQL (utile pour le dev)
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.main.banner-mode=off